### ISSUE TITLE
ISSUE: FadeIn animation for Nav Sidebar in v3.2.0

### ISSUE THREAD

**Issue by Serge3d** [jeroennoten/Laravel-AdminLTE#608]
In v3.1.1:
```css
/*_main-sidebar.scss:69*/
.nav-sidebar .nav-link p {
    display: inline-block;
    margin: 0;
}
```
In v3.2.0 animation fadeIn appeared and now left sidebar items `<p>` blink on page load :
```css
/*_variables.scss:36*/
.nav-sidebar .nav-link p {
    display: inline-block;
    -webkit-animation-name: fadeIn;
    animation-name: fadeIn;
    -webkit-animation-duration: .3s;
    animation-duration: .3s;
    -webkit-animation-fill-mode: both;
    animation-fill-mode: both;
    margin: 0;
}
```

And when use .nav-collapse-hide-child class in config 'classes_sidebar_nav' child submenu blink when show:
```css
/*_bootstrap_variables.scss:12*/
.nav-collapse-hide-child .menu-open > .nav-treeview {
	/* max-height: -webkit-min-content; */
	/* max-height: -moz-min-content; */
	max-height: min-content;
	-webkit-animation-name: fadeIn;
	animation-name: fadeIn;
	-webkit-animation-duration: .3s;
	animation-duration: .3s;
	-webkit-animation-fill-mode: both;
	animation-fill-mode: both;
}
```
