### ISSUE TITLE
Migrate to New PHP Analysis of Scrutinizer

### ISSUE THREAD

**Issue by Shidersz** [jeroennoten/Laravel-AdminLTE#628]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| Laravel Version         | Not relevant
| Project Version         | v3.3.0

Should we migrate to the [new PHP Analysis of scrutinizer](https://scrutinizer-ci.com/docs/tools/php/php-analyzer/guides/migrate_to_new_php_analysis)? The migration is very easy, it consist of adding the next code to the configuration file (`.scrutinizer.yml`):

```yml
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
```

I have [tested](https://scrutinizer-ci.com/g/Shidersz/Laravel-AdminLTE/inspections/75c9b45d-01ff-4b4d-8ac4-9659658a1661) this on my local fork, and it worked just fine, but i'm not sure if there is anything redundant now. What you say about this?
